//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSpiritHelper.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(BlackSpiritHelper.Core.CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.TimerDataViewModel TimerData {
            get {
                return ((global::BlackSpiritHelper.Core.TimerDataViewModel)(this["TimerData"]));
            }
            set {
                this["TimerData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(BlackSpiritHelper.Core.CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.PreferencesDataViewModel PreferencesData {
            get {
                return ((global::BlackSpiritHelper.Core.PreferencesDataViewModel)(this["PreferencesData"]));
            }
            set {
                this["PreferencesData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(BlackSpiritHelper.Core.CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.OverlayDataViewModel OverlayData {
            get {
                return ((global::BlackSpiritHelper.Core.OverlayDataViewModel)(this["OverlayData"]));
            }
            set {
                this["OverlayData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(BlackSpiritHelper.Core.CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.ScheduleDataViewModel ScheduleData {
            get {
                return ((global::BlackSpiritHelper.Core.ScheduleDataViewModel)(this["ScheduleData"]));
            }
            set {
                this["ScheduleData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(BlackSpiritHelper.Core.CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.ApplicationCookies ApplicationCookies {
            get {
                return ((global::BlackSpiritHelper.Core.ApplicationCookies)(this["ApplicationCookies"]));
            }
            set {
                this["ApplicationCookies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(BlackSpiritHelper.Core.CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.WatchdogDataViewModel WatchdogData {
            get {
                return ((global::BlackSpiritHelper.Core.WatchdogDataViewModel)(this["WatchdogData"]));
            }
            set {
                this["WatchdogData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(BlackSpiritHelper.Core.CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.ApmCalculatorDataViewModel ApmCalculatorData {
            get {
                return ((global::BlackSpiritHelper.Core.ApmCalculatorDataViewModel)(this["ApmCalculatorData"]));
            }
            set {
                this["ApmCalculatorData"] = value;
            }
        }
    }
}
