//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSpiritHelper.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte LastOpenedPage {
            get {
                return ((byte)(this["LastOpenedPage"]));
            }
            set {
                this["LastOpenedPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.TimerDesignModel TimerDesignModel {
            get {
                return ((global::BlackSpiritHelper.Core.TimerDesignModel)(this["TimerDesignModel"]));
            }
            set {
                this["TimerDesignModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.PreferencesDesignModel PreferencesDesignModel {
            get {
                return ((global::BlackSpiritHelper.Core.PreferencesDesignModel)(this["PreferencesDesignModel"]));
            }
            set {
                this["PreferencesDesignModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BlackSpiritHelper.Core.OverlayDesignModel OverlayDesignModel {
            get {
                return ((global::BlackSpiritHelper.Core.OverlayDesignModel)(this["OverlayDesignModel"]));
            }
            set {
                this["OverlayDesignModel"] = value;
            }
        }
    }
}
